[[modules]]
name = "normalizer"
binary = "target/debug/normalizer"
socket = "/tmp/genesis-core/normalizer.sock"

[[modules]]
name = "tokenizer"
binary = "target/debug/tokenizer"
socket = "/tmp/genesis-core/tokenizer.sock"

[[modules]]
name = "parser"
binary = "target/debug/parser"
socket = "/tmp/genesis-core/parser.sock"

[[modules]]
name = "evaluator"
binary = "target/debug/evaluator"
socket = "/tmp/genesis-core/evaluator.sock"
